server:
  port: 8081
spring:
  application:
    name: SOLICITUDES
  devtools:
    add-properties: false
  sql:
    init:
      mode: always

adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: postgres
    schema: public # You may need to adjust this value if your schema is different
    username: postgres
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

security:
  jwt:
    secret: 1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7a8b9c0d1e2f

auth:
  service:
    base-url: http://localhost:8080