server:
  port: 8085
spring:
  application:
    name: "solicitudes"
  devtools:
    add-properties: false
  sql:
    init:
      mode: "always"
      schema-locations: "classpath:database/schema.sql"
      data-locations: "classpath:database/data.sql"
adapters:
  r2dbc:
    host: "${ADAPTERS_R2DBC_HOST:localhost}"
    port: "${ADAPTERS_R2DBC_PORT:5432}"
    database: "${ADAPTERS_R2DBC_DATABASE:postgres}"
    schema: "${ADAPTERS_R2DBC_SCHEMA:public}"
    username: "${ADAPTERS_R2DBC_USERNAME:postgres}"
    password: "${ADAPTERS_R2DBC_PASSWORD:123456}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
security:
  jwt:
    secret: "1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7a8b9c0d1e2f"
auth:
  service:
    base-url: "http://localhost:8080"
adapter:
  sqs:
    region: "us-east-2"
    queueUrl: "https://sqs.us-east-2.amazonaws.com/155290702720/ColaNotificacionEmail"
    capacity-queue-url: "https://us-east-2.queue.amazonaws.com/155290702720/CapacidadEndeudamiento"
springdoc:
  api-docs:
    path: "/v3/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    operationsSorter: "method"
    tagsSorter: "alpha"
  show-actuator: true
logging.level:
  co.com.projectve.sqs.sender: "DEBUG"
entrypoint:
  sqs:
    region: "us-east-2"
    #endpoint: "http://localhost:4566"
    queueUrl: "https://sqs.us-east-2.amazonaws.com/155290702720/CapacidadResultados"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 30
    numberOfThreads: 1
