server:
  port: 8080
spring:
  application:
    name: SOLICITUDES
  devtools:
    add-properties: false
  sql:
    init:
      mode: always

adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: postgres
    schema: public # You may need to adjust this value if your schema is different
    username: postgres
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"