name=PropertiesConfig
property.filename=logs

appenders=console

appender.console.type=Console
appender.console.name=STDOUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

# Loggers por paquete del proyecto
logger.co.com.projectve.api.name=co.com.projectve.api
logger.co.com.projectve.api.level=trace
logger.co.com.projectve.api.additivity=true
logger.co.com.projectve.api.appenderRef.console.ref=STDOUT

logger.co.com.projectve.r2dbc.name=co.com.projectve.r2dbc
logger.co.com.projectve.r2dbc.level=debug
logger.co.com.projectve.r2dbc.additivity=true
logger.co.com.projectve.r2dbc.appenderRef.console.ref=STDOUT

# Spring Security (para ver flujo del JWT)
logger.org.springframework.security.name=org.springframework.security
logger.org.springframework.security.level=debug
logger.org.springframework.security.additivity=false
logger.org.springframework.security.appenderRef.console.ref=STDOUT

# Raíz
rootLogger.level=info
rootLogger.appenderRefs=stdout
rootLogger.appenderRef.stdout.ref=STDOUT


